"""
Iztack-Finance - Smart Shopping List Service v2
Generates shopping lists from consumption cycles and recent purchase history.
"""
import logging
from datetime import date, timedelta, datetime
from typing import List, Dict, Optional
from dataclasses import dataclass

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc

from app.database.models import (
    Ticket,
    ConsumptionCycle,
    ShoppingList,
    ShoppingItem as ShoppingItemModel,
    ShoppingListStatus,
    ShoppingItemStatus,
)
from app.modules.clasificacion.service import ClassificationService

logger = logging.getLogger(__name__)


@dataclass
class ShoppingItem:
    name: str
    category: str = ""
    quantity: float = 1.0
    unit: str = "pza"
    estimated_price: float = 0.0
    preferred_store: str = ""
    product_link: str = ""
    priority: int = 0
    auto_generated: bool = False


@dataclass
class GeneratedList:
    """Complete shopping list generated by the system."""
    id: Optional[str]
    title: str
    items: List[ShoppingItem]
    estimated_total: float
    store_grouping: Dict[str, List[ShoppingItem]]
    created_at: str
    source: str = "auto"


class ShoppingListService:
    """Intelligent shopping list generator backed by real purchase data."""

    # Fallback consumption cycles (days) for common products when no history exists
    DEFAULT_CYCLES = {
        "leche": 7, "pan": 7, "huevo": 7, "tortilla": 7,
        "fruta": 7, "verdura": 7, "carne": 7, "pollo": 7,
        "pescado": 7, "yogur": 7, "agua": 7,
        "arroz": 15, "frijol": 15, "pasta": 15, "aceite": 15,
        "cereal": 15, "galleta": 15, "queso": 15,
        "jabon": 30, "shampoo": 30, "crema dental": 30,
        "papel higienico": 30, "detergente": 30, "suavizante": 30,
        "cloro": 30, "limpiador": 30,
    }

    DEFAULT_QUANTITIES = {
        "leche": (2, "lt"), "pan": (1, "pza"), "huevo": (12, "pza"),
        "fruta": (1, "kg"), "verdura": (1, "kg"), "carne": (1, "kg"),
        "pollo": (1, "kg"), "pescado": (1, "kg"), "yogur": (6, "pza"),
        "agua": (1, "garrafon"), "arroz": (2, "kg"), "frijol": (1, "kg"),
        "pasta": (2, "pza"), "aceite": (1, "lt"), "cereal": (1, "pza"),
        "galleta": (1, "pza"), "queso": (0.5, "kg"), "jabon": (2, "pza"),
        "shampoo": (1, "pza"), "crema dental": (1, "pza"),
        "papel higienico": (12, "pza"), "detergente": (1, "pza"),
        "suavizante": (1, "lt"), "cloro": (1, "lt"), "limpiador": (1, "pza"),
    }

    def __init__(self, db: AsyncSession):
        self.db = db

    async def generate_weekly_list(
        self,
        user_id: str,
        title: Optional[str] = None,
    ) -> GeneratedList:
        """
        Generate a weekly shopping list based on consumption cycles and defaults.
        Persists the list and its items in the database.
        """
        items: List[ShoppingItem] = []

        # 1. Add items from learned consumption cycles that are due soon
        cycle_items = await self._get_items_from_cycles(user_id)
        items.extend(cycle_items)

        # 2. Add default essentials if the user has no/few learned cycles
        if len(items) < 5:
            items.extend(self._get_default_items())

        # Deduplicate by normalized name, keeping the first (learned has priority)
        seen = set()
        unique_items = []
        for item in items:
            key = item.name.lower().strip()
            if key not in seen:
                seen.add(key)
                unique_items.append(item)
        items = unique_items

        # Estimate total
        estimated_total = sum(i.estimated_price for i in items)

        # Persist
        shopping_list = ShoppingList(
            user_id=user_id,
            title=title or f"Lista Semanal - {date.today().strftime('%d/%m/%Y')}",
            status=ShoppingListStatus.DRAFT.value,
            estimated_total=estimated_total,
            generated_by="auto",
        )
        self.db.add(shopping_list)
        await self.db.flush()  # to obtain shopping_list.id

        for item in items:
            db_item = ShoppingItemModel(
                shopping_list_id=shopping_list.id,
                product_name=item.name,
                category=item.category,
                quantity=item.quantity,
                unit=item.unit,
                estimated_price=item.estimated_price,
                preferred_store=item.preferred_store,
                product_link=item.product_link,
                priority=item.priority,
                status=ShoppingItemStatus.PENDING.value,
            )
            self.db.add(db_item)

        await self.db.commit()
        await self.db.refresh(shopping_list)

        return GeneratedList(
            id=shopping_list.id,
            title=shopping_list.title,
            items=items,
            estimated_total=estimated_total,
            store_grouping=self._group_by_store(items),
            created_at=shopping_list.created_at.isoformat(),
            source="auto",
        )

    async def get_current_list(self, user_id: str) -> Optional[GeneratedList]:
        """Return the most recent non-completed shopping list for the user."""
        result = await self.db.execute(
            select(ShoppingList)
            .where(
                ShoppingList.user_id == user_id,
                ShoppingList.status.in_([
                    ShoppingListStatus.DRAFT.value,
                    ShoppingListStatus.FAMILY_REVIEW.value,
                    ShoppingListStatus.APPROVED.value,
                    ShoppingListStatus.IN_PROGRESS.value,
                ]),
            )
            .order_by(desc(ShoppingList.created_at))
            .limit(1)
        )
        shopping_list = result.scalar_one_or_none()
        if not shopping_list:
            return None

        items = [
            ShoppingItem(
                name=item.product_name,
                category=item.category or "",
                quantity=item.quantity or 1.0,
                unit=item.unit or "pza",
                estimated_price=item.estimated_price or 0.0,
                preferred_store=item.preferred_store or "",
                product_link=item.product_link or "",
                priority=item.priority or 0,
                auto_generated=(shopping_list.generated_by == "auto"),
            )
            for item in shopping_list.items
        ]

        return GeneratedList(
            id=shopping_list.id,
            title=shopping_list.title,
            items=items,
            estimated_total=sum(i.estimated_price for i in items),
            store_grouping=self._group_by_store(items),
            created_at=shopping_list.created_at.isoformat(),
            source=shopping_list.generated_by,
        )

    async def _get_items_from_cycles(self, user_id: str) -> List[ShoppingItem]:
        """Query consumption cycles that are due within the next week."""
        next_week = date.today() + timedelta(days=7)
        result = await self.db.execute(
            select(ConsumptionCycle).where(
                ConsumptionCycle.user_id == user_id,
                ConsumptionCycle.is_active == True,
                ConsumptionCycle.auto_generate == True,
                ConsumptionCycle.next_estimated_purchase.isnot(None),
                ConsumptionCycle.next_estimated_purchase <= next_week,
            )
        )
        cycles = result.scalars().all()

        items = []
        for cycle in cycles:
            qty = cycle.preferred_quantity or 1.0
            unit = cycle.preferred_unit or "pza"
            if qty == 1.0 and cycle.product_name.lower() in self.DEFAULT_QUANTITIES:
                qty, unit = self.DEFAULT_QUANTITIES[cycle.product_name.lower()]

            items.append(ShoppingItem(
                name=cycle.product_name,
                category=cycle.product_category or "",
                quantity=qty,
                unit=unit,
                estimated_price=cycle.avg_unit_price or 0.0,
                preferred_store=cycle.preferred_store or "",
                priority=5,
                auto_generated=True,
            ))
        return items

    def _get_default_items(self) -> List[ShoppingItem]:
        """Return default essential items when no cycles are learned yet."""
        items = []
        for name, days in list(self.DEFAULT_CYCLES.items())[:10]:
            qty, unit = self.DEFAULT_QUANTITIES.get(name, (1, "pza"))
            classification = ClassificationService.classify_product(name, price=0)
            items.append(ShoppingItem(
                name=name.title(),
                category=classification.get("category", ""),
                quantity=qty,
                unit=unit,
                priority=10,
                auto_generated=True,
            ))
        return items

    @staticmethod
    def _group_by_store(items: List[ShoppingItem]) -> Dict[str, List[ShoppingItem]]:
        """Group items by preferred store (fallback to 'Sin tienda preferida')."""
        groups: Dict[str, List[ShoppingItem]] = {}
        for item in items:
            store = item.preferred_store or "Sin tienda preferida"
            groups.setdefault(store, []).append(item)
        return groups

    def suggest_savings(self, list_total: float, budget: float) -> Dict:
        """Suggest savings if list exceeds budget."""
        if budget <= 0:
            return {}

        overage = list_total - budget
        if overage <= 0:
            return {
                "within_budget": True,
                "remaining": round(budget - list_total, 2),
                "message": "✅ La lista está dentro del presupuesto.",
            }

        return {
            "within_budget": False,
            "overage": round(overage, 2),
            "message": (
                f"⚠️ La lista excede el presupuesto por ${overage:.0f}. "
                f"Sugerencia: Revisa los items de menor prioridad."
            ),
            "suggestions": [
                "Revisa los items marcados como 'auto' que puedan esperar",
                "Compara precios entre tiendas",
                "Considera opciones de marca propia",
            ],
        }

    def format_for_printer(self, shopping_list: GeneratedList, width: int = 57) -> str:
        """Format shopping list for thermal printer (57mm or 80mm)."""
        lines = []
        line_width = 32 if width == 57 else 48

        lines.append("=" * line_width)
        lines.append("LISTA DE COMPRAS".center(line_width))
        lines.append(shopping_list.created_at.center(line_width))
        lines.append("=" * line_width)
        lines.append("")

        for store, store_items in shopping_list.store_grouping.items():
            lines.append(f"🏪 {store}")
            lines.append("-" * line_width)
            for i, item in enumerate(store_items, 1):
                price_str = f"${item.estimated_price:.0f}" if item.estimated_price else ""
                line = f"{i}. {item.name}"
                if item.quantity > 1:
                    line += f" x{item.quantity:.0f} {item.unit}"
                if price_str:
                    line += f" {price_str}"
                lines.append(line[:line_width])
            lines.append("")

        lines.append("-" * line_width)
        lines.append(f"TOTAL ESTIMADO: ${shopping_list.estimated_total:.2f}".center(line_width))
        lines.append("")
        lines.append("=" * line_width)
        lines.append("[ ] Comprado  [ ] Pendiente".center(line_width))
        lines.append("")
        lines.append(f"Impreso: {datetime.now().strftime('%d/%m/%Y %H:%M')}".center(line_width))
        lines.append("=" * line_width)

        return "\n".join(lines)

    async def update_consumption_cycles(self, user_id: str, ticket: Ticket):
        """Update or create consumption cycles after a new ticket is saved."""
        today = date.today()
        for product in ticket.products:
            if not product.is_consumable:
                continue

            name_lower = product.name.lower()
            result = await self.db.execute(
                select(ConsumptionCycle).where(
                    ConsumptionCycle.user_id == user_id,
                    ConsumptionCycle.product_name.ilike(product.name),
                )
            )
            cycle = result.scalar_one_or_none()

            if cycle:
                # Update existing cycle
                cycle.purchase_count += 1
                cycle.total_quantity_purchased = (cycle.total_quantity_purchased or 0) + product.quantity
                cycle.avg_unit_price = product.unit_price or product.total_price
                if cycle.last_purchase_date:
                    days_since = (ticket.purchase_date - cycle.last_purchase_date).days
                    if days_since > 0:
                        old_avg = cycle.avg_days_between_purchases or days_since
                        cycle.avg_days_between_purchases = int(
                            (old_avg * (cycle.purchase_count - 1) + days_since) / cycle.purchase_count
                        )
                else:
                    cycle.avg_days_between_purchases = ClassificationService.estimate_consumption_cycle(
                        product.name, product.category or ""
                    )
                cycle.last_purchase_date = ticket.purchase_date
                if cycle.avg_days_between_purchases:
                    cycle.next_estimated_purchase = ticket.purchase_date + timedelta(
                        days=cycle.avg_days_between_purchases
                    )
                cycle.preferred_quantity = product.quantity
                cycle.preferred_unit = product.unit
                cycle.product_category = product.category
            else:
                # Create new cycle
                estimated_days = ClassificationService.estimate_consumption_cycle(
                    product.name, product.category or ""
                )
                cycle = ConsumptionCycle(
                    user_id=user_id,
                    product_name=product.name,
                    product_category=product.category,
                    preferred_store=ticket.store_name,
                    avg_days_between_purchases=estimated_days,
                    last_purchase_date=ticket.purchase_date,
                    next_estimated_purchase=(
                        ticket.purchase_date + timedelta(days=estimated_days)
                        if estimated_days else None
                    ),
                    purchase_count=1,
                    total_quantity_purchased=product.quantity,
                    avg_unit_price=product.unit_price or product.total_price,
                    preferred_quantity=product.quantity,
                    preferred_unit=product.unit,
                    is_active=True,
                    auto_generate=True,
                )
                self.db.add(cycle)

        await self.db.commit()
