"""
Sistema Financiero - Smart Shopping List Service
Generates intelligent shopping lists based on consumption cycles and family voting.
"""
import logging
from datetime import date, datetime, timedelta
from typing import Optional, List, Dict
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class ShoppingItem:
    name: str
    category: str = ""
    quantity: float = 1.0
    unit: str = "pza"
    estimated_price: float = 0.0
    preferred_store: str = ""
    product_link: str = ""
    priority: int = 0
    auto_generated: bool = False


@dataclass
class GeneratedList:
    """Complete shopping list generated by the system."""
    title: str
    items: List[ShoppingItem]
    estimated_total: float
    store_grouping: Dict[str, List[ShoppingItem]]
    created_at: str
    source: str = "auto"


class ShoppingListService:
    """
    Intelligent shopping list generator.
    Detects consumption cycles, generates lists, manages family approval.
    """

    # Default consumption cycles (days) for common products
    DEFAULT_CYCLES = {
        "leche": 7, "pan": 7, "huevo": 7, "tortilla": 7,
        "fruta": 7, "verdura": 7, "carne": 7, "pollo": 7,
        "pescado": 7, "yogur": 7, "agua": 7,
        "arroz": 15, "frijol": 15, "pasta": 15, "aceite": 15,
        "cereal": 15, "galleta": 15, "queso": 15,
        "jabon": 30, "shampoo": 30, "crema dental": 30,
        "papel higienico": 30, "detergente": 30, "suavizante": 30,
        "cloro": 30, "limpiador": 30,
    }

    async def generate_weekly_list(self, user_id: str) -> GeneratedList:
        """
        Generate a weekly shopping list based on consumption patterns.
        In production, queries the database for actual purchase history.
        """
        # TODO: Query consumption_cycles and tickets from database
        items = []
        
        # Add essential weekly items
        weekly_items = [
            ("Leche", "alimentos", 2, "lt"),
            ("Pan", "alimentos", 1, "pza"),
            ("Huevo", "alimentos", 12, "pza"),
            ("Frutas y Verduras", "alimentos", 1, "kg"),
            ("Carne/Pollo", "alimentos", 1, "kg"),
        ]
        
        for name, cat, qty, unit in weekly_items:
            items.append(ShoppingItem(
                name=name, category=cat, quantity=qty, unit=unit,
                priority=10, auto_generated=True
            ))
        
        # Group by store
        store_groups = {"Walmart": items}
        
        total = sum(item.estimated_price for item in items)
        
        return GeneratedList(
            title=f"Lista Semanal - {date.today().strftime('%d/%m/%Y')}",
            items=items,
            estimated_total=total,
            store_grouping=store_groups,
            created_at=datetime.now().isoformat(),
            source="auto"
        )

    async def generate_detailed_list(self, user_id: str, 
                                       include_stores: List[str] = None) -> GeneratedList:
        """Generate a detailed shopping list organized by store."""
        base_list = await self.generate_weekly_list(user_id)
        
        # Add bi-weekly/monthly items
        monthly_items = [
            ShoppingItem("Arroz", "alimentos", 2, "kg", 45, auto_generated=True),
            ShoppingItem("Frijol", "alimentos", 1, "kg", 35, auto_generated=True),
            ShoppingItem("Aceite", "alimentos", 1, "lt", 28, auto_generated=True),
            ShoppingItem("Papel Higiénico", "higiene", 12, "pza", 85, auto_generated=True),
            ShoppingItem("Detergente", "limpieza", 1, "pza", 65, auto_generated=True),
            ShoppingItem("Jabón de manos", "higiene", 2, "pza", 18, auto_generated=True),
            ShoppingItem("Pasta dental", "higiene", 1, "pza", 35, auto_generated=True),
        ]
        
        all_items = base_list.items + monthly_items
        
        # Re-group by store
        store_groups = {
            "Walmart": all_items,
        }
        
        total = sum(i.estimated_price for i in all_items)
        
        return GeneratedList(
            title=f"Lista Completa - {date.today().strftime('%d/%m/%Y')}",
            items=all_items,
            estimated_total=total,
            store_grouping=store_groups,
            created_at=datetime.now().isoformat(),
            source="auto"
        )

    def suggest_savings(self, list_total: float, budget: float) -> Dict:
        """Suggest savings if list exceeds budget."""
        if budget <= 0:
            return {}
        
        overage = list_total - budget
        if overage <= 0:
            return {
                "within_budget": True,
                "remaining": round(budget - list_total, 2),
                "message": "✅ La lista está dentro del presupuesto."
            }
        
        return {
            "within_budget": False,
            "overage": round(overage, 2),
            "message": (
                f"⚠️ La lista excede el presupuesto por ${overage:.0f}. "
                f"Sugerencia: Revisa los items de menor prioridad."
            ),
            "suggestions": [
                "Revisa los items marcados como 'auto' que puedan esperar",
                "Compara precios entre tiendas",
                "Considera opciones de marca propia",
            ]
        }

    def format_for_printer(self, shopping_list: GeneratedList, 
                            width: int = 57) -> str:
        """Format shopping list for thermal printer (57mm or 80mm)."""
        lines = []
        line_width = 32 if width == 57 else 48
        
        # Header
        lines.append("=" * line_width)
        lines.append("LISTA DE COMPRAS".center(line_width))
        lines.append(shopping_list.created_at.center(line_width))
        lines.append("=" * line_width)
        lines.append("")
        
        # Items grouped by store
        for store, items in shopping_list.store_grouping.items():
            lines.append(f"🏪 {store}")
            lines.append("-" * line_width)
            
            for i, item in enumerate(items, 1):
                price_str = f"${item.estimated_price:.0f}" if item.estimated_price else ""
                line = f"{i}. {item.name}"
                if item.quantity > 1:
                    line += f" x{item.quantity:.0f} {item.unit}"
                if price_str:
                    line += f" {price_str}"
                lines.append(line[:line_width])
            
            lines.append("")
        
        # Total
        lines.append("-" * line_width)
        lines.append(f"TOTAL ESTIMADO: ${shopping_list.estimated_total:.2f}".center(line_width))
        lines.append("")
        
        # Checkbox footer
        lines.append("=" * line_width)
        lines.append("[ ] Comprado  [ ] Pendiente".center(line_width))
        lines.append("")
        lines.append(f"Impreso: {datetime.now().strftime('%d/%m/%Y %H:%M')}".center(line_width))
        lines.append("=" * line_width)
        
        return "\n".join(lines)

    async def check_missing_purchases(self, user_id: str, 
                                        shopping_list_id: str) -> List[str]:
        """
        Check which items from a shopping list haven't been purchased yet.
        Cross-references with recent tickets.
        """
        # TODO: Query tickets and shopping items from database
        return []

    async def get_family_approval_status(self, list_id: str) -> Dict:
        """Get the status of family approval for a shopping list."""
        return {
            "total_members": 0,
            "approved": 0,
            "rejected": 0,
            "pending": 0,
            "changes_suggested": [],
        }